# Generated by Django for Render migration fix

from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('magasin', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []


